# Generated by Django 6.0.5 on 2026-06-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_author_rename_decription_post_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('bog', 'bog'), ('pirincimpe', 'pirincimpe'), ('nothing', 'nothing')])),
            ],
        ),
    ]
